module.exports = {
  CHANGE_STATE: "CHANGE_STATE",
  SIGNUP_RESPONSE_SUCCESS: "SIGNUP_RESPONSE_SUCCESS",
  SIGNUP_RESPONSE_ERROR: "SIGNUP_RESPONSE_ERROR",
  HIDE_SIGNUP_ERROR: "HIDE_SIGNUP_ERROR"
}